{"name": "Session scheduling", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'datetime.date'\n", "trace": "  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\ClientScheduleSession.py\", line 47, in step_impl\n    allure.attach(today,today)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 179, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_behave\\listener.py\", line 172, in attach_data\n    self.logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\reporter.py\", line 119, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\logger.py\", line 62, in report_attached_data\n    attached_file.write(body)\n"}, "steps": [{"name": "Given Client should logged in with valid credential \"wipofi2562@iistoria.com\" , \"Qwerty@123\"", "status": "passed", "start": 1639455345915, "stop": 1639455370338}, {"name": "When Schedule first session of client", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'datetime.date'\n", "trace": "  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\ClientScheduleSession.py\", line 47, in step_impl\n    allure.attach(today,today)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 179, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_behave\\listener.py\", line 172, in attach_data\n    self.logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\reporter.py\", line 119, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\logger.py\", line 62, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"name": 