{"name": "Session scheduling by coach", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=96.0.4664.93)\n\n", "trace": "  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\SessionScheduling.py\", line 96, in step_impl\n    context.driver.find_element_by_xpath(selectaday).click()\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Coach should logged in with valid credential \"yemefis666@keagenan.com\" , \"Qwerty@123\"", "status": "passed", "start": 1639542630259, "stop": 1639542666683}, {"name": "When Schedule session with client \"Mabixep\"", "status": "passed", "start": 1639542666684, "stop": 1639542691431}, {"name": "Then Session scheduled with client", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=96.0.4664.93)\n\n", "trace": "  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\SessionScheduling.py\", line 96, in step_impl\n    context.driver.find_element_by_xpath(selectaday).click()\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\kanaka\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1639542691432, "stop": 1639542703926}], "start": 1639542630253, "stop": 1639542703927, "uuid": "0040b00e-9f0f-4007-a9af-bb28f19e6b13", "historyId": "4db3addb1470ed705bff6ed57f9d2884", "fullName": "Session scheduling across all 3 three user roles: Session scheduling by coach", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Session scheduling across all 3 three user roles"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}